fix: cursor position adjustment after exiting alt screen
charmbracelet/bubbletea pull request #1241
Opened 2024-11-16 22:41 UTC by semihbkgr

When exiting alternate screen mode, the cursor was not properly adjusted, which caused terminal content to be either overwritten (if the current line count was greater than before entering alt screen) or leftover lines to remain at the top (if the current line count was smaller). To fix this, we save the number of lines rendered before entering alternate screen mode. When exiting, we compare the current line count with the saved value and adjust the cursor position accordingly, ensuring correct positioning and preventing both overwriting and leftover lines.

fixes #1013

2024-11-16 23:14 UTC, semihbkgr commented
In my understanding, the source of this issue appears to be that the terminal automatically moves the cursor back to its position, where it was before entering alt screen mode, when exiting.

2024-11-17 22:38 UTC, meowgorithm commented
Thanks for this, @semihbkgr. Can you also paste in some code for a minimally reproducible example? It would also be good to know if this is a regression in `v1.2.0`.

2024-11-18 19:56 UTC, semihbkgr commented
Hi @meowgorithm 

> Can you also paste in some code for a minimally reproducible example?

There is already an [example](https://github.com/charmbracelet/bubbletea/issues/1013#issue-2290061726) in the issue mentioned in the description. It was a real case we encountered in [kubectl-klock](https://github.com/applejag/kubectl-klock/issues/93). However, I will share a simplified example to reproduce the bug more easily, which directly highlights the problematic situation 👍

> It would also be good to know if this is a regression in v1.2.0.

The issue dates back to older versions. The issue was created on May 10, indicating it was first observed in `v0.26.2` or earlier.

2024-11-18 21:15 UTC, meowgorithm commented
Thanks for that; we're taking a look.

2024-11-19 14:59 UTC, aymanbagabas approved these changes
LGTM, thank you, @semihbkgr!

2024-11-19 15:32 UTC, merged

2024-11-19 15:33 UTC, meowgorithm commented
Awesome fix, @semihbkgr: _thank you_. We'll get a patch release out today.

2024-11-19 22:02 UTC, meowgorithm commented
Alright, [`v1.2.3`](https://github.com/charmbracelet/bubbletea/releases/tag/v1.2.3), containing the fix, is available now. Thanks for the fix @semihbkgr!

2024-11-21 15:32 UTC, unitsvc commented
`clear` screen , then tea.EnterAltScreen -> tea.ExitAltScreen, sometimes it does not work on mac or linux systems

2024-12-25 12:13 UTC, 40004930 requested changes
<?xml الإصدار="1.0" الترميز="UTF-8"?>
<rss الإصدار="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <القناة>
    <title>وثائق السجل الفيدرالي المنشورة في 25 نوفمبر 2024 أو بعده، من مكتب البيئة، ووزارة الطاقة، والتي تعتبر أجندتها الموحدة المرتبطة بها مهمة بموجب الأمر التنفيذي 12866</title>
    <link>https://www.federalregister.gov/api/v1/documents.rss?conditions%5Bagencies%5D%5B%5D=environment-office-energy-department&conditions%5Bsignificant%5D=1</link>
    <description>المستندات الموجودة في هذه الخلاصة مستمدة من FederalRegister.gov الذي يعرض نسخة غير رسمية من السجل الفيدرالي اليومي على شبكة الإنترنت. كما يتوفر الإصدار الإلكتروني الرسمي بتنسيق PDF كرابط من موقع FederalRegister.gov على الويب. لمزيد من المعلومات، يُرجى الاطلاع على https://www.federalregister.gov/reader-aids/policy/legal-status.</description>
  </القناة>
</rss>

- [ ]