Updated Realtime Example
charmbracelet/bubbletea pull request #1243
Opened 2024-11-19 18:54 UTC by FFCoder

Per Issue #1242 updated the real time example to grab some random chat messages and send it down the channel. This will be used to demonstrate how a production application could send messages over a channel. 

Largely, I tried to limit changes as much as possible other than what is needed. I'm still new-ish to Golang so I welcome criticism or if we want to go another way with this I'm happy to change!

2024-11-19 22:59 UTC, mdepot commented
Thanks, this is already helpful.  Prior to this there were a number of places where the channel was just defined as struct{}.  Now it's obvious that responsMsg is the type that should be on the channel, and that is key to understanding this example.

2024-11-19 23:24 UTC, mdepot commented
In retrospect, since responseMsg was already defined then just substituting `chan responseMsg` for all the `chan struct{}` and `sub <- responseMsg{}` for `sub <- struct{}{}` might have made it clear enough, even without passing any data inside the responseMsg.

2024-11-19 23:55 UTC, mdepot requested changes
It looks like this would still work ok if ChatMessage was private (lower case).  If not, please help me understand why it might be good to leave it exported.

Also, printing Last Message could use a leading space for alignment.

2025-02-25 14:09 UTC, FFCoder commented
@meowgorithm  or @aymanbagabas  would either of you mind reviewing this?

2025-03-19 18:30 UTC, closed without merging

2025-03-19 19:44 UTC, meowgorithm commented
Hey @FFCoder. Apologies for the delay on this one: we've been very backlogged. This is a helpful PR and wed be happy to merge it with some changes (notably, I'd use the `tea.Println()` command to print messages).

If you're willing to reopen it we'd be happy to make those changes and merge it.