docs: creating nested models
charmbracelet/bubbletea pull request #346
Opened 2022-06-17 19:14 UTC by bashbunni

## Changes:
- [x] add info on working with nested models
- [x] add docs folder

2022-07-13 16:41 UTC, bashbunni commented
hey @maaslalani great suggestion. I actually found some typos while moving the code over to an example :joy: what do you think about these changes? I feel like these docs will become more substantial as we get more questions and as we get feedback. Just pushed the latest changes

2022-07-13 16:48 UTC, maaslalani commented
Looks awesome @bashbunni !!!

2022-07-13 16:48 UTC, maaslalani approved these changes

2022-07-13 16:59 UTC, meowgorithm requested changes
A few quick notes here:

* Please do make sure the example code runs (I'm sure it's still a work-in-progress)
* I would be great to show how one can use a state member in `Update`, in addition to `View`. For example, to change key handling when a section of the app changes focus, since that will be a super common need.

2022-08-05 16:42 UTC, bashbunni commented
tbd in dev meeting. I'd like some feedback on writing effective comments in the code and whether or not this example should use `tea.Batch` or return commands. I feel like returning commands makes the flow a bit more obvious, but using `tea.Batch` is the cleaner solution. I can make this PR a single commit as well if that's preferred.

2022-08-10 17:10 UTC, bashbunni commented
This example no longer manages state from a main model. That is shown in the `composable-view` branch.

2025-02-05 15:29 UTC, closed without merging