(feat): Add option to set max FPS
charmbracelet/bubbletea pull request #578
Opened 2022-10-26 09:18 UTC by tomfeigin

Solves issue #577 

Added the `WithMaxFPS` option to bubbletea program struct, if it is set with a non 0 value it will set the maximum interval at which the view is updated, if it is not set or set to 0, the interval will be the `defaultFramerate` constant.

2022-12-06 08:16 UTC, tomfeigin commented
Hey @muesli did you get a chance to look at this PR? 
We really want to stop using our fork and use the official repo and this tiny change blocks us

2023-01-23 15:01 UTC, meowgorithm commented
I think this one makes sense. My only thought is that we probably want to clamp the values to keep things from accidentally getting too outta control. So maybe the lower bound is at `1` (to prevent division by zero) and the upper bound is at `120`.

And if we're clamping the values an `int` _probably_ makes more sense for convenience as it's the Go numeric default.

2023-01-23 15:04 UTC, meowgorithm requested changes

2023-01-23 15:04 UTC, meowgorithm commented on tea.go
> +	frameRate time.Duration
I'd also name this var `framerate` (all lowercase) for consistency with the other values.

2023-04-30 18:46 UTC, tomfeigin commented
@meowgorithm hey, can we merge this, please? Should I change anything?

2023-05-10 01:25 UTC, meowgorithm commented
> @meowgorithm hey, can we merge this, please? Should I change anything?

Hey there! Thanks for the ping and sorry for the delay on this. Will give it a re-review this week.

2023-05-11 01:34 UTC, meowgorithm commented
Thanks for your patience, @tomfeigin. I've rebased `master` onto this branch and made a few small edits and I believe this one is ready to go. I'm not able to push my changes to the branch on your repo, however.

Do you mind either ticking the box to allow me to push _or_ resetting to the [`fps`](https://github.com/charmbracelet/bubbletea/tree/fps) branch on your end? Alternatively, I could just open a new PR as well.

Anyway, let me know.

2023-05-11 04:13 UTC, tomfeigin commented
@meowgorithm Thank you! Done :)

2023-05-11 04:18 UTC, meowgorithm approved these changes

2023-05-11 04:20 UTC, meowgorithm commented
> @meowgorithm Thank you! Done :)

Awesome. Would ideally like to get @muesli’s approval as well.

Mues, I played with this a bit and for me it’s working great.

2023-06-05 16:53 UTC, tomfeigin commented
@muesli @meowgorithm, any updates on this? We really want to stop maintaining our fork

2023-06-06 15:49 UTC, merged