docs: add nachrichten to Bubble Tea in the Wild
charmbracelet/bubbletea pull request #902
Opened 2024-01-14 12:21 UTC by zMoooooritz

A little TUI I have written with bubbletea - [nachrichten](https://github.com/zMoooooritz/nachrichten)

2024-03-01 19:05 UTC, meowgorithm commented on README.md
> +* [nachrichten](https://github.com/zMoooooritz/nachrichten): stay informed without leaving your command line
Mind updating this to something more specific like the following?

> access up-to-date news in German provided by the [Tagesschau](https://www.tagesschau.de/)

2024-03-01 19:06 UTC, meowgorithm requested changes
This looks so cool! Happy to merge if you don't mind making the description more specific.

2024-03-04 17:07 UTC, maaslalani commented
Thank you for the contribution @zMoooooritz, nice work! ❤️

2024-03-04 17:08 UTC, merged

2024-03-04 20:10 UTC, zMoooooritz commented
@meowgorithm Thank you for creating this awesome framework
and thanks to @maaslalani for integrating the improved description
I have been busy the last day and have unfortunately not seen your messages