docs: add link to laboon project
charmbracelet/bubbletea pull request #948
Opened 2024-03-08 07:38 UTC by arisnacg

Hello, Bubbletea team. Thank you for your great library 🎉

I created a Bubbletea project for managing Docker containers that look like Docker Desktop. I added the link in the Wild section of the README. 

Preview of my Bubbletea project:

![laboon](https://raw.githubusercontent.com/arisnacg/laboon/main/demo.gif)

2024-03-08 14:56 UTC, meowgorithm requested changes
This looks great! In addition to the copy edit suggestion, do you mind putting this in alphabetical order?

2024-03-08 14:56 UTC, meowgorithm commented on README.md
> +* [laboon](https://github.com/arisnacg/laboon): an TUI that similliar Docker Desktop
```suggestion
* [laboon](https://github.com/arisnacg/laboon): a Docker-desktop-style container manager
```

2024-03-08 22:31 UTC, arisnacg commented on README.md
> +* [laboon](https://github.com/arisnacg/laboon): an TUI that similliar Docker Desktop
Sure!

2024-03-09 15:16 UTC, meowgorithm commented
Awesome, thank you!

2024-03-09 15:16 UTC, merged